### PR TITLE
fix: update volume after starting a new track

### PR DESCRIPTION
**Pull request by maslade**
Am I pulling to the right branch?

I'm not sure if this is the most elegant way to solve the problem. I'm still learning the order of events and flow of the code. But this did fix it in my testing. I tested directly on their app (https://browse.theclass.dev/videos/1665692438559) and used Charles to swap out a customized version of our SDK.

Without this change, I consistently got silence at track 3, and with some debug logging I was able to confirm the root cause Matt and I suspected. After this change, I heard track 3 just fine.

The logging I added tracked the three audio instances (preparing, fading, active) and their respective volume over time. I observed:
1. While track #1 was playing, `preparing` was the actively playing audio element. Proven by adjusting the volume of the music and seeing this element's `volume` change.
2. When track #1 reached the end, and our padding logic kicked in to add silence, `preparing.volume` was set to 0.
3. When track #2 began, it used `active`. At this point `active.volume` was set to the correct volume that I wanted (0.05) and `preparing.volume` was still 0.
4. When track #3 began, it used the `preparing` slot, which was still set to 0. Once I added this fix, `preparing.volume` received the correct volume once track #3 began playing.

Unanswered questions: why does this occur in *their* app, but not the JSBin player using our SDK? It might just be that I wasn't triggering the silence padding logic with the JSBin test, which is a necessary part of this.

### CODE REVIEW

**Review by mishugana — CHANGES_REQUESTED** [review]
i would still remove manual2 from this pr before merge

**Comment by mishugana** [comment]
I would get this out in front of Mikhail asap, but personally i want to make sure that gain works properly, and fade in and fade out work properly.

**Comment by maslade** [comment]
Agreed. I'll reach out this morning.  Reading manual2, it's helpful for testing, but I can remove the credentials from it so it's not insensitive. Eventually I think this page (or manual, I didn't look closely at it) can serve as a basis for running automated tests, by adding more diagnostic output and more buttons to trigger various things.

**Comment by maslade** [comment]
My updates:
* Add tags/commits for previous versions that were published. Unfortunately they aren't correct, meaning the commit tagged `timing.2` is not what we actually published as `timing.2`. However those versions (`.2-.3`) were published, I can't tell what code was actually shipped. But the latest version (`1.103.5-timing.4`) is accurately tagged.
* Removes credentials from manual2

Before I merge this I want to let The Class help us test it. I will also be removing the debugging stuff that's been added.

**Comment by maslade** [comment]
@eml @mishugana I just pushed an update that I believe fixes the crossfade issue, but I would definitely appreciate another set of eyes. This PR changes manual.html to provide a little more debugging output, which is really helpful for seeing the state of the audio groups as they change (without having to use breakpoints or console logging).

I found a few problems.

1. `Speaker.startNextMS` wasn't not accounting for `fadeOutSeconds` in all cases. I fixed that [here](https://github.com/feedfm/Javascript-SDK/pull/33/files#diff-10e3ec7c5e2e48c70d05eaa0576cc723aaf54fe858c19713ec292e617f624b43R1339-R1341).
2. Once that was honoring `fadeOutSeconds`, I noticed the actual fading also didn't work. What I was seeing is when the next song started, it was advancing `this.startNextMS` to the *next* track. That was throwing off the fade-out calculations which were based on `this.startNextMS` ([here](https://github.com/feedfm/Javascript-SDK/pull/33/files#diff-10e3ec7c5e2e48c70d05eaa0576cc723aaf54fe858c19713ec292e617f624b43L732-L737)).

I didn't want to introduce more state, like `previousSoneStartMS`... it just seemed messy. I created a class that encapsulates all of the logic for animating a change in volume over time. It's a lot easier to reason about but from what I gleaned it doesn't sacrifice any functionality. I ripped most of the fade out logic out of `_onAudioTimeUpdateEvent` and some of it out of `_setVolume`.

If this were more permanent, and this pattern is good, I'd want to extend it to fadeIn and fading between stations as well, but here I'm just trying to focus on fixing the bug and this was the best way I could find to do it.

**Pull request merged**
